"""user table update

Revision ID: 4f0d83be8e44
Revises: d2a5593d1247
Create Date: 2020-11-22 08:30:07.107495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0d83be8e44'
down_revision = 'd2a5593d1247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userIdNumber', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userIdNumber')
    # ### end Alembic commands ###
