"""table version update

Revision ID: 5e0f9996e945
Revises: b65a416b1ee0
Create Date: 2020-11-08 09:11:58.017419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e0f9996e945'
down_revision = 'b65a416b1ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('productCode', sa.String(length=30), nullable=False))
    op.drop_column('Products', 'pCode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('pCode', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('Products', 'productCode')
    # ### end Alembic commands ###
