"""user table update

Revision ID: 8d983bdafaab
Revises: af738719a6db
Create Date: 2020-11-22 08:32:32.250855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d983bdafaab'
down_revision = 'af738719a6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userIdNumber', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('usernameEmail', sa.String(length=200), nullable=False),
    sa.Column('usernamePhoneNumber', sa.String(length=40), nullable=False),
    sa.Column('usernamePassSalt', sa.String(length=30), nullable=False),
    sa.Column('usernamePassHash', sa.String(length=300), nullable=False),
    sa.Column('userRole', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userRole'], ['userRole.roleId'], ),
    sa.PrimaryKeyConstraint('userIdNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
