"""user table update

Revision ID: af738719a6db
Revises: 4f0d83be8e44
Create Date: 2020-11-22 08:32:10.385741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af738719a6db'
down_revision = '4f0d83be8e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('usernameEmail', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('usernamePhoneNumber', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('usernamePassSalt', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('usernamePassHash', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('userRole', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('userIdNumber', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['userRole'], ['userRole.roleId'], name='users_ibfk_1'),
    sa.PrimaryKeyConstraint('username'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
