"""table version one

Revision ID: b65a416b1ee0
Revises: 89582d5764e0
Create Date: 2020-11-08 09:09:24.052534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65a416b1ee0'
down_revision = '89582d5764e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.String(length=40), nullable=False),
    sa.Column('categoryVat', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('categotyDiscount', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.PrimaryKeyConstraint('categoryId')
    )
    op.create_table('paymentMethod',
    sa.Column('paymentMethodId', sa.Integer(), nullable=False),
    sa.Column('paymentMethodName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('paymentMethodId')
    )
    op.create_table('userRole',
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('roleName', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('roleId')
    )
    op.create_table('Products',
    sa.Column('pCode', sa.String(length=30), nullable=False),
    sa.Column('productName', sa.String(length=60), nullable=False),
    sa.Column('productDescription', sa.String(length=200), nullable=True),
    sa.Column('productPrice', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('productCategory', sa.Integer(), nullable=True),
    sa.Column('productQuantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productCategory'], ['Category.categoryId'], ),
    sa.PrimaryKeyConstraint('pCode')
    )
    op.create_table('ReceptBook',
    sa.Column('receptId', sa.Integer(), nullable=False),
    sa.Column('purchaseAmount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('purchaseType', sa.Integer(), nullable=True),
    sa.Column('dateOfPurchase', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['purchaseType'], ['paymentMethod.paymentMethodId'], ),
    sa.PrimaryKeyConstraint('receptId')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('usernameEmail', sa.String(length=200), nullable=False),
    sa.Column('usernamePhoneNumber', sa.String(length=40), nullable=False),
    sa.Column('usernamePassSalt', sa.String(length=30), nullable=False),
    sa.Column('usernamePassHash', sa.String(length=300), nullable=False),
    sa.Column('userRole', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userRole'], ['userRole.roleId'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('Creditor',
    sa.Column('creditorId', sa.String(length=30), nullable=False),
    sa.Column('creditorFirstName', sa.String(length=50), nullable=False),
    sa.Column('creditorSecondName', sa.String(length=50), nullable=False),
    sa.Column('receptId', sa.Integer(), nullable=True),
    sa.Column('dateDuePayment', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['receptId'], ['ReceptBook.receptId'], ),
    sa.PrimaryKeyConstraint('creditorId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Creditor')
    op.drop_table('users')
    op.drop_table('ReceptBook')
    op.drop_table('Products')
    op.drop_table('userRole')
    op.drop_table('paymentMethod')
    op.drop_table('Category')
    # ### end Alembic commands ###
