"""table version update

Revision ID: d2a5593d1247
Revises: 5e0f9996e945
Create Date: 2020-11-08 09:17:20.803756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2a5593d1247'
down_revision = '5e0f9996e945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Category', sa.Column('categoryDiscount', sa.Numeric(precision=2, scale=1), nullable=False))
    op.drop_column('Category', 'categotyDiscount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Category', sa.Column('categotyDiscount', mysql.DECIMAL(precision=2, scale=1), nullable=False))
    op.drop_column('Category', 'categoryDiscount')
    # ### end Alembic commands ###
